/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frm;

import cls.DBConnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.util.Random;
/**
 *
 * @author muham
 */
import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;

public class frmRegistracija extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    
    String from, to, host, sub, content;
    
    
    public frmRegistracija() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imeLabel = new javax.swing.JLabel();
        prezimeLabel = new javax.swing.JLabel();
        sifraLabel = new javax.swing.JLabel();
        sifra2Label = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        imeTxtBox = new javax.swing.JTextField();
        prezimeTxtBox = new javax.swing.JTextField();
        emailTxtBox = new javax.swing.JTextField();
        btnRegistracija = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sifraTxtBox = new javax.swing.JPasswordField();
        sifra2TxtBox = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        imeLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        imeLabel.setText("Ime");

        prezimeLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        prezimeLabel.setText("Prezime");

        sifraLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sifraLabel.setText("Sifra");

        sifra2Label.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sifra2Label.setText("Ponovi sifru");

        emailLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        emailLabel.setText("Email");

        imeTxtBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        imeTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                imeTxtBoxKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                imeTxtBoxKeyTyped(evt);
            }
        });

        prezimeTxtBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        prezimeTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                prezimeTxtBoxKeyPressed(evt);
            }
        });

        emailTxtBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        emailTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailTxtBoxKeyPressed(evt);
            }
        });

        btnRegistracija.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegistracija.setText("Registruj se");
        btnRegistracija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistracijaActionPerformed(evt);
            }
        });

        jLabel1.setText("Imas nalog?");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("PRIJAVI SE");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        sifraTxtBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        sifra2TxtBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/library-icon-10.png"))); // NOI18N
        jLabel3.setText("Biblioteka");
        jLabel3.setIconTextGap(25);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistracija, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(emailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emailTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(imeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(imeTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prezimeLabel)
                            .addComponent(sifraLabel)
                            .addComponent(sifra2Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sifra2TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sifraTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prezimeTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imeLabel)
                    .addComponent(imeTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prezimeLabel)
                    .addComponent(prezimeTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sifraLabel)
                    .addComponent(sifraTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sifra2Label)
                    .addComponent(sifra2TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistracija, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    Connection kon = null;
    PreparedStatement ps;
    ResultSet rs;
    
    public static boolean validacijaUnosa(String ime, String prezime, String sifra, String sifra2, String email){
        if (ime.isEmpty() || prezime.isEmpty() || sifra.isEmpty() || sifra2.isEmpty() || email.isEmpty()) {
            return false;
        }
        return true;
    };
    
    public static boolean podudarnostSifri(String sifra, String sifra2){
        if (sifra.equals(sifra2)) {
            return true;
        }
        return false;
    }; 
//    
    public boolean provjeraMaila(String mail){
        String sql = "SELECT `email` FROM `korisnici` WHERE email = ?";
            try {
                kon = DBConnect.uspostaviKonekciju();
                ps = kon.prepareStatement(sql);
                ps.setString(1, mail);
                rs = ps.executeQuery();
                
                if(rs.next()){
                    return false;
                }
                return true;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Greška u komunikaciji sa serverom -> "+e.getMessage());
                return false;
            }
    }; 
    
    public void popunjavanjePolja(JTextField trenutno, JTextField sljedece, java.awt.event.KeyEvent evt){
        trenutno.setBackground(Color.white);
        int key = evt.getKeyCode();
        if(key==10){
            if(trenutno.getText().isEmpty()){
                trenutno.requestFocus();
                trenutno.setBackground(Color.red);
            } else {
                sljedece.requestFocus();
            }
        }
    }
    
    private void btnRegistracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistracijaActionPerformed
        // TODO add your handling code here:
        imeTxtBox.setBackground(Color.white);
        prezimeTxtBox.setBackground(Color.white);
        emailTxtBox.setBackground(Color.white);
        sifraTxtBox.setBackground(Color.white);
        sifra2TxtBox.setBackground(Color.white);
               
        String ime = imeTxtBox.getText();
        String prezime = prezimeTxtBox.getText();
        String email = emailTxtBox.getText();
        String sifra = sifraTxtBox.getText();
        String sifra2 = sifra2TxtBox.getText();
        
        Random random = new Random();
        int OTP = random.nextInt(900000) + 100000;
        
        from = "softverskotest@gmail.com";
        to = email;
        host = "localhost";
        sub = "Verifikacija registracije za biblioteku";
        content = "Vas kod za verifikaciju za biblioteku je " + String.valueOf(OTP) + " Unesite ga u formu za verifikaciju kako biste potvrdili registraciju";
        
        Properties p = new Properties();
        p.put("mail.smtp.auth", "true");
        p.put("mail.smtp.starttls.enable", "true");
        p.put("mail.smtp.host", "smtp.gmail.com");
        p.put("mail.smtp.port", "587");
        
        Session s = Session.getDefaultInstance(p, new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication("softverskotest@gmail.com", "hciadmguqihvylsi");
            }
        
        });       
        
        if(validacijaUnosa(ime, prezime, sifra, sifra2, email)&&podudarnostSifri(sifra, sifra2)&&provjeraMaila(email)){
            try {
                MimeMessage m = new MimeMessage(s);
                m.setFrom(from);
                m.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
                m.setSubject(sub);
                m.setText(content);
            
                Transport.send(m);
                
                String sql = "INSERT INTO verifikacije(mail, OTP) VALUES (?,?)";
                try {
                    kon = DBConnect.uspostaviKonekciju();
                    ps = kon.prepareStatement(sql);
                    ps.setString(1, email);
                    ps.setString(2, String.valueOf(OTP));
                    ps.executeUpdate();
                    this.setVisible(false);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Greška u komunikaciji sa serverom -> "+e.getMessage());
                }
                
                new frmVerifikacija().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            if(!validacijaUnosa(ime, prezime, sifra, sifra2, email)){
                if(ime.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Polje za ime je prazno");
                    imeTxtBox.requestFocus();
                    imeTxtBox.setBackground(Color.red);
                } else if (prezime.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Polje za prezime je prazno");
                    prezimeTxtBox.requestFocus();
                    prezimeTxtBox.setBackground(Color.red);
                } else if (sifra.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Polje za sifru je prazno");
                    sifraTxtBox.requestFocus();
                    sifraTxtBox.setBackground(Color.red);
                } else if (sifra2.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Ponovi sifru");
                    sifra2TxtBox.requestFocus();
                    sifra2TxtBox.setBackground(Color.red);
                } else if (email.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Polje za email je prazno");
                    emailTxtBox.requestFocus();
                    emailTxtBox.setBackground(Color.red);
                }
            }
            else if (!podudarnostSifri(sifra, sifra2)){
                JOptionPane.showMessageDialog(null, "Sifre se ne podudaraju");
                sifraTxtBox.requestFocus();
                sifraTxtBox.setBackground(Color.red);
                sifra2TxtBox.setBackground(Color.red);
            }
            else if (!provjeraMaila(email)){
                JOptionPane.showMessageDialog(null, "Mail je vec u upotrebi");
                emailTxtBox.requestFocus();
                emailTxtBox.setBackground(Color.red); 
            }
        }
        
        
        
    }//GEN-LAST:event_btnRegistracijaActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new frmLogin().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void imeTxtBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_imeTxtBoxKeyPressed
        // TODO add your handling code here:
        popunjavanjePolja(imeTxtBox, prezimeTxtBox, evt);
    }//GEN-LAST:event_imeTxtBoxKeyPressed

    private void prezimeTxtBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prezimeTxtBoxKeyPressed
        // TODO add your handling code here:
        popunjavanjePolja(prezimeTxtBox, sifraTxtBox, evt);
    }//GEN-LAST:event_prezimeTxtBoxKeyPressed

    private void emailTxtBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTxtBoxKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if(key==10){
            if(emailTxtBox.getText().isEmpty()){
                emailTxtBox.requestFocus();
                emailTxtBox.setBackground(Color.red);
            } else {
                emailTxtBox.setBackground(Color.white);
                btnRegistracija.doClick();
            }
        }
    }//GEN-LAST:event_emailTxtBoxKeyPressed

    private void imeTxtBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_imeTxtBoxKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_imeTxtBoxKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistracija().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistracija;
    private javax.swing.JLabel emailLabel;
    public static javax.swing.JTextField emailTxtBox;
    private javax.swing.JLabel imeLabel;
    public static javax.swing.JTextField imeTxtBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel prezimeLabel;
    public static javax.swing.JTextField prezimeTxtBox;
    private javax.swing.JLabel sifra2Label;
    public static javax.swing.JPasswordField sifra2TxtBox;
    private javax.swing.JLabel sifraLabel;
    public static javax.swing.JPasswordField sifraTxtBox;
    // End of variables declaration//GEN-END:variables
}
