/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frm;

import cls.DBConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author muham
 */
public class frmUrediPozajmnicu extends javax.swing.JFrame {

    /**
     * Creates new form frmUrediPozajmnicu
     */
    public frmUrediPozajmnicu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKorisnici = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblKnjige = new javax.swing.JTable();
        btnOdustani = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPretrazi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPretrazi1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblKorisnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ime", "Prezime", "Email"
            }
        ));
        tblKorisnici.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKorisniciMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKorisnici);

        tblKnjige.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ime", "Autor", "Kategorija", "Kolicina"
            }
        ));
        tblKnjige.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKnjigeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblKnjige);

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        btnDodaj.setText("Uredi");
        btnDodaj.setEnabled(false);
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        jLabel1.setText("Datum uzimanja:");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/library-icon-10.png"))); // NOI18N
        jLabel3.setText("Biblioteka");
        jLabel3.setIconTextGap(25);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("PRETRAZI KNJIGE:");

        txtPretrazi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretraziKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("PRETRAZI KORISNIKE:");

        txtPretrazi1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretrazi1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPretrazi)))
                            .addComponent(btnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPretrazi1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(449, 449, 449)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(txtPretrazi))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtPretrazi1)))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajEnable(){
        int selectedRow1 = tblKorisnici.getSelectedRow();
        int selectedRow2 = tblKnjige.getSelectedRow();
        if (selectedRow1 != -1 && selectedRow2 != -1) { 
            btnDodaj.setEnabled(true);            
        } else {
            btnDodaj.setEnabled(false);            
        }
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        ucitajKorisnike();
        ucitajKnjige();

        selectRowByValue(frmAdminPanel.tblPrikaz.getValueAt(frmAdminPanel.tblPrikaz.getSelectedRow(), 1), 2, tblKorisnici);
        selectRowByValue(frmAdminPanel.tblPrikaz.getValueAt(frmAdminPanel.tblPrikaz.getSelectedRow(), 2), 0, tblKnjige);

       ucitajDatum();
        
    }//GEN-LAST:event_formWindowOpened

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new frmAdminPanel().setVisible(true);
        frmAdminPanel.btnPozajmnice.doClick();
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        // TODO add your handling code here:
        try {
            String korisnikId = null, knjigaId = null;
            kon = DBConnect.uspostaviKonekciju();
            ps = kon.prepareStatement("SELECT id FROM korisnici WHERE email=?");
            ps.setString(1, String.valueOf(tblKorisnici.getValueAt(tblKorisnici.getSelectedRow(), 2)));
            rs=ps.executeQuery();
            if(rs.next()){
                korisnikId = rs.getString("id");
            }
            ps = kon.prepareStatement("SELECT id FROM knjige WHERE ime=? AND autor=?");
            ps.setString(1, String.valueOf(tblKnjige.getValueAt(tblKnjige.getSelectedRow(), 0)));
            ps.setString(2, String.valueOf(tblKnjige.getValueAt(tblKnjige.getSelectedRow(), 1)));
            rs=ps.executeQuery();
            if(rs.next()){
                knjigaId = rs.getString("id");
            }
            ps = kon.prepareStatement("UPDATE pozajmnice INNER JOIN korisnici ON korisnici.id = pozajmnice.korisnik_id INNER JOIN knjige ON knjige.id = pozajmnice.knjiga_id SET korisnik_id=?,knjiga_id=?, datum = ? WHERE korisnici.email = ? and knjige.ime = ?");
            ps.setString(1, korisnikId);
            ps.setString(2, knjigaId);
            ps.setString(3, new SimpleDateFormat("yyyy-MM-dd").format(jDateChooser1.getDate()));
            ps.setString(4,String.valueOf(frmAdminPanel.tblPrikaz.getValueAt(frmAdminPanel.tblPrikaz.getSelectedRow(), 1)));
            ps.setString(5,String.valueOf(frmAdminPanel.tblPrikaz.getValueAt(frmAdminPanel.tblPrikaz.getSelectedRow(), 2)));
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Pozajmnica je promijenjena", "Promjena pozajmnice", JOptionPane.INFORMATION_MESSAGE);

            this.setVisible(false);
            new frmAdminPanel().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Greška u komunikaciji sa serverom -> "+e.getMessage());
        }

    }//GEN-LAST:event_btnDodajActionPerformed

    private void txtPretraziKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretraziKeyReleased
        // TODO add your handling code here:
        try {
            kon = DBConnect.uspostaviKonekciju();
            ps = kon.prepareStatement("SELECT * FROM korisnici WHERE ime LIKE ? or prezime LIKE ? or email LIKE ?");
            ps.setString(1, "%" + txtPretrazi.getText() + "%"); 
            ps.setString(2, "%" + txtPretrazi.getText() + "%");
            ps.setString(3, "%" + txtPretrazi.getText() + "%");
            rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblKorisnici.getModel();
            model.setRowCount(0);
            model.setColumnCount(0);
            model.addColumn("Ime");
            model.addColumn("Prezime");
            model.addColumn("Mail");
            model.addColumn("Admin");
            while(rs.next()){
                String isAdmin = "";
                if(rs.getString("isAdmin").equals("1")){
                    isAdmin = "Administrator";
                } else {
                    isAdmin = "Član";
                }
                model.addRow(new String[]{rs.getString("ime"),rs.getString("prezime"),rs.getString("email"),isAdmin});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_txtPretraziKeyReleased

    private void txtPretrazi1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretrazi1KeyReleased
        // TODO add your handling code here:
            try {
            kon = DBConnect.uspostaviKonekciju();
            ps = kon.prepareStatement("SELECT knjige.ime, knjige.autor, knjige.kolicina, kategorije.naziv AS kategorija FROM knjige INNER JOIN kategorije ON knjige.kategorija = kategorije.id WHERE ime LIKE ? OR autor LIKE ?");
            ps.setString(1, "%" + txtPretrazi1.getText() + "%"); 
            ps.setString(2, "%" + txtPretrazi1.getText() + "%");
            rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblKnjige.getModel();
            model.setRowCount(0);
            model.setColumnCount(0);
            model.addColumn("Ime");
            model.addColumn("Autor");
            model.addColumn("Kategorija");
            model.addColumn("Kolicina");
            while(rs.next()){
                model.addRow(new String[]{rs.getString("ime"),rs.getString("autor"),rs.getString("kategorija"),rs.getString("kolicina")});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_txtPretrazi1KeyReleased

    private void tblKorisniciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKorisniciMouseClicked
        // TODO add your handling code here:
        btnDodajEnable();
    }//GEN-LAST:event_tblKorisniciMouseClicked

    private void tblKnjigeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKnjigeMouseClicked
        // TODO add your handling code here:
        btnDodajEnable();
    }//GEN-LAST:event_tblKnjigeMouseClicked

        Connection kon = null;
    PreparedStatement ps;
    ResultSet rs;
    
    private void selectRowByValue(Object value, int column, JTable table) {
        for (int row = 0; row < table.getRowCount(); row++) {
            Object cellValue = table.getValueAt(row, column);
            if (cellValue != null && cellValue.equals(value)) {
                table.setRowSelectionInterval(row, row);
                break;
            }
        }
    }
    
    
    
    private void ucitajKnjige(){
        try {
            kon = DBConnect.uspostaviKonekciju();
            ps = kon.prepareStatement("SELECT knjige.ime, knjige.autor, knjige.kolicina, kategorije.naziv AS kategorija FROM knjige INNER JOIN kategorije ON knjige.kategorija = kategorije.id");
            rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblKnjige.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString("ime"),rs.getString("autor"),rs.getString("kategorija"),rs.getString("kolicina")});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    private void ucitajDatum(){
        String datum = null;
        try {
            kon = DBConnect.uspostaviKonekciju();
            ps = kon.prepareStatement("SELECT datum FROM pozajmnice INNER JOIN korisnici ON korisnici.id = pozajmnice.korisnik_id INNER JOIN knjige ON knjige.id = pozajmnice.knjiga_id WHERE korisnici.email = ? and knjige.ime = ?");
            ps.setString(1,String.valueOf(frmAdminPanel.tblPrikaz.getValueAt(frmAdminPanel.tblPrikaz.getSelectedRow(), 1)));
            ps.setString(2,String.valueOf(frmAdminPanel.tblPrikaz.getValueAt(frmAdminPanel.tblPrikaz.getSelectedRow(), 2)));
            rs = ps.executeQuery();
            if(rs.next()){
                datum = rs.getString("datum");
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                Date date = dateFormat.parse(datum);
                jDateChooser1.setDate(date);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (ParseException ex) {
            Logger.getLogger(frmUrediPozajmnicu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void ucitajKorisnike(){
        try {
            kon = DBConnect.uspostaviKonekciju();
            ps = kon.prepareStatement("SELECT * FROM korisnici");
            rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblKorisnici.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString("ime"),rs.getString("prezime"),rs.getString("email")});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUrediPozajmnicu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUrediPozajmnicu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUrediPozajmnicu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUrediPozajmnicu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUrediPozajmnicu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnOdustani;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblKnjige;
    private javax.swing.JTable tblKorisnici;
    private javax.swing.JTextField txtPretrazi;
    private javax.swing.JTextField txtPretrazi1;
    // End of variables declaration//GEN-END:variables
}
