/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frm;

import cls.DBConnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author muham
 */
public class frmVerifikacija extends javax.swing.JFrame {

    /**
     * Creates new form frmVerifikacija
     */
    public frmVerifikacija() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        OTPTxtBox = new javax.swing.JTextField();
        btnVerifikuj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><div style=\"text-align:center\">Na vaš mail je poslana jednokratna šifra. <br>Unesite je u polje ispod da biste verifikovali mail</div></html>");
        jLabel1.setMaximumSize(new java.awt.Dimension(400, 17));
        jLabel1.setMinimumSize(new java.awt.Dimension(400, 17));

        OTPTxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        OTPTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                OTPTxtBoxKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                OTPTxtBoxKeyTyped(evt);
            }
        });

        btnVerifikuj.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnVerifikuj.setText("Verifikuj");
        btnVerifikuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifikujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OTPTxtBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVerifikuj)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OTPTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerifikuj)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    Connection kon = null;
    PreparedStatement ps;
    ResultSet rs;
    
    String OTP;
    int isAdmin;
   
   
    private void btnVerifikujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifikujActionPerformed
        // TODO add your handling code here:       
        
        String ime = frmRegistracija.imeTxtBox.getText();
        String prezime = frmRegistracija.prezimeTxtBox.getText();
        String email = frmRegistracija.emailTxtBox.getText();
        char[] sifra = frmRegistracija.sifraTxtBox.getPassword();
        
        if(OTPTxtBox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Polje za ime je prazno");
            OTPTxtBox.requestFocus();
            OTPTxtBox.setBackground(Color.red);
        } else {
            String sql = "SELECT `OTP` FROM `verifikacije` WHERE mail=?";
            try {
                kon = DBConnect.uspostaviKonekciju();
                ps = kon.prepareStatement(sql);
                ps.setString(1, email);
                rs = ps.executeQuery();
                while(rs.next())
                {
                    OTP = String.valueOf(rs.getInt(1));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Greška u komunikaciji sa serverom -> "+e.getMessage());
            }
        
        }
        
        if(OTP.equals(OTPTxtBox.getText())){
            try {
                String sql = "INSERT INTO korisnici(ime, prezime, email, sifra) VALUES (?,?,?,?)";
                kon = DBConnect.uspostaviKonekciju();
                ps = kon.prepareStatement(sql);
                ps.setString(1, ime);
                ps.setString(2, prezime);
                ps.setString(3, email);
                ps.setString(4,String.valueOf(sifra));
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Korisnik je registrovan", "Registracija korisnika", JOptionPane.INFORMATION_MESSAGE);
                
                new frmUserPanel().setVisible(true);
                this.setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Greška u komunikaciji sa serverom -> "+e.getMessage());
            }
            try {
                String sql = "DELETE FROM verifikacije where mail = ?";
                kon = DBConnect.uspostaviKonekciju();
                ps = kon.prepareStatement(sql);
                ps.setString(1, email);
                ps.executeUpdate();
    
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Greška u komunikaciji sa serverom -> "+e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "OTP nije tacan, pokusaj opet");
            OTPTxtBox.requestFocus();
        }

        
        
    }//GEN-LAST:event_btnVerifikujActionPerformed

    private void OTPTxtBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OTPTxtBoxKeyPressed
        // TODO add your handling code here:
       int key = evt.getKeyCode();
        if(key==10){
            if(OTPTxtBox.getText().isEmpty()){
                OTPTxtBox.requestFocus();
            } else {
                btnVerifikuj.doClick();
            }
        }
    }//GEN-LAST:event_OTPTxtBoxKeyPressed

    private void OTPTxtBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OTPTxtBoxKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume(); // Odbacuje unos ako nije broj
        }
    }//GEN-LAST:event_OTPTxtBoxKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVerifikacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVerifikacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVerifikacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVerifikacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVerifikacija().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField OTPTxtBox;
    private javax.swing.JButton btnVerifikuj;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
